#include<gl.h>
#include<string>
#include<iterator>
#include<fstream>
#include<iostream>
#include<vector>
#include<matrix.h>
#include<math.h>
#include<GL/Keyboard/key/input.h>
#include<GL/View/camera.h>